/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spark;

public class App {
    public String getGreeting() {
        return "Hello World from DevOps-Team";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Spark.get("/welcome", (req, res) -> {
            return "Hallo from DevOps";
        });

        Spark.get("/welcomeUser", (req, res) -> {
            String user = req.queryParams("user");
            return "Hallo "+user+" from DevOps";
        });

        Spark.get("/sum", (req, res) -> {
            int val1 = Integer.parseInt(req.queryParams("val1"));
            int val2 = Integer.parseInt(req.queryParams("val2"));
            return Integer.toString(val1+val2);
        });
    }
}
